import QtQuick
import Quickshell
import Quickshell.Io
import qs.Commons
import "Model.js" as Model

// Drives the repository-bundled `omarchy-jackal` operator CLI and the release's own generated
// capability inventory, and holds the parsed result.
//
// JACKAL is strict about the difference between what a surface DECLARES and
// what a run ESTABLISHED. Package presence is never a functional pass, and a
// declared class is never evidence that the class executed. This service keeps
// the two apart rather than flattening them into a boolean, and treats "not
// established here" as its own state, so the bar can never render an unearned
// pass.
Item {
  id: root

  property var settings: ({})

  // ---- Function: established only by tools executed in this session --------

  // Last `doctor --json` payload, with a receipt timestamp stamped on arrival.
  // Null until a probe completes in this shell session.
  property var report: null
  // Last `verify` payload — a runtime-tree check, separate from doctor.
  property var verifyReport: null
  property double receivedAtMs: 0
  property string lastError: ""
  property string actionStatus: ""

  // Ticks so age text and the staleness rule re-evaluate without a probe.
  property double nowMs: 0

  readonly property int refreshIntervalSec: intSetting("refreshIntervalSec", 900, 60, 86400)
  readonly property int staleAfterSec: intSetting("staleAfterSec", 2400, 120, 172800)
  readonly property bool probeOnOpen: setting("probeOnOpen", true) === true

  readonly property bool busy: doctorProcess.running || verifyProcess.running
  // Not named `state`: Item already owns that property.
  readonly property string evidenceState: Model.classify(report, verifyReport, nowMs, staleAfterSec)
  readonly property var probeRows: Model.probeRows(report)
  readonly property int probeTotal: probeRows.length
  readonly property int probePassed: Model.passCount(report)

  readonly property string epoch: report && report.capability
    ? String(report.capability.package_epoch || "") : ""
  readonly property string packageSha: report && report.capability
    ? String(report.capability.package_sha256 || "") : ""
  readonly property string doctorRuntimePath: report && report.capability
    ? String(report.capability.runtime_path || "") : ""
  readonly property bool z3Present: !!(report && report.capability && report.capability.z3_present)
  readonly property bool anubisPresent: !!(report && report.capability && report.capability.anubis_compiler_present)
  readonly property bool identityMatch: !!(report && report.identity_match)
  readonly property string verdict: report ? String(report.doctor_verdict || "") : ""
  readonly property string hostText: report && report.host
    ? (String(report.host.system || "") + " " + String(report.host.machine || "")).trim() : ""
  readonly property string verifyText: verifyReport ? String(verifyReport.verify || "") : ""
  readonly property string runtimePath: verifyReport ? String(verifyReport.runtime || "") : ""

  // ---- Capability: the release's own declared surface ---------------------
  //
  // `capability_inventory_v1.json` is generated by the release, not written by
  // hand and not inferred here. It is read only from the runtime whose epoch
  // the doctor probe established: a surface we cannot name is a surface we must
  // not summarise.

  property var inventory: null
  readonly property var familyRows: inventory ? Model.familyRows(inventory) : []
  readonly property var profileRows: Model.profileRows(inventory)
  readonly property int declaredToolCount: inventory ? inventory.toolCount : 0
  readonly property string catalogSha: inventory ? String(inventory.catalogSha || "") : ""
  readonly property bool everyToolDeclaresRefused: inventory
    ? inventory.everyToolDeclaresRefused === true : false
  // Named, so a surface where the law has stopped holding can say which tool
  // broke it instead of going quiet.
  readonly property var toolsWithoutRefused: inventory
    ? inventory.toolsWithoutRefused : []

  // The engine's own governing non-claim, verbatim from `jackal maturity`.
  property string nonClaim: ""

  // ---- Latest results ------------------------------------------------------
  //
  // Recent JACKAL answers, read from the ledger the MCP wrapper writes. This is
  // the only part of the panel that reports work done OUTSIDE this widget, so
  // it is read fresh from disk and never cached across a failed read: a stale
  // answer presented as recent would be its own small lie.
  property var results: []
  property bool resultsReadQueued: false
  readonly property string resultsPath:
    Quickshell.env("HOME") + "/.local/state/jackal/results.jsonl"
  readonly property string receiptsDir:
    Quickshell.env("HOME") + "/.local/state/jackal/receipts"

  // ---- Verification: the front door ---------------------------------------
  //
  // The artifact comes from the clipboard; the AUTHORIZATION comes from an
  // operator-owned file. They must not come from the same place: expectations
  // taken from the artifact under review would make every check pass and mean
  // nothing. `verify_artifact.py` keeps them apart structurally and refuses
  // when the authorization is absent.

  property var verifyResult: null
  readonly property bool verifyBusy: artifactProcess.running
  readonly property string defaultExpectationsPath:
    Quickshell.env("HOME") + "/.config/omarchy/jackal-expectations.json"
  readonly property string expectationsPath: {
    var configured = String(setting("expectationsPath", "")).trim()
    return configured === "" ? defaultExpectationsPath : configured
  }
  // This file's own directory, so the router is found wherever the plugin sits.
  readonly property string pluginDir:
    String(Qt.resolvedUrl(".")).replace(/^file:\/\//, "").replace(/\/$/, "")

  // Prefer the canonical runtime path returned by the bundled operator CLI.
  // The epoch-derived location remains only for compatibility with older
  // doctor payloads already present while the plugin hot-reloads.
  readonly property string runtimeDir: doctorRuntimePath !== ""
    ? doctorRuntimePath
    : (epoch !== ""
       ? Quickshell.env("HOME") + "/.local/share/JACKAL/runtimes/" + epoch
       : "")

  onRuntimeDirChanged: {
    // A runtime we can no longer name is a runtime whose declarations we must
    // not keep showing.
    if (runtimeDir === "") {
      inventory = null
      nonClaim = ""
    } else {
      readInventory()
      readNonClaim()
    }
  }

  function setting(name, fallback) {
    var value = settings ? settings[name] : undefined
    return value === undefined || value === null ? fallback : value
  }

  function intSetting(name, fallback, min, max) {
    var n = parseInt(String(setting(name, fallback)), 10)
    if (!isFinite(n)) n = fallback
    if (n < min) n = min
    if (n > max) n = max
    return n
  }

  function stale() {
    if (!report) return true
    return (nowMs - receivedAtMs) / 1000 > staleAfterSec
  }

  function refresh() {
    if (doctorProcess.running) return
    doctorProcess.reset()
    actionStatus = "Probing…"
    doctorProcess.running = true
  }

  function refreshIfStale() {
    // The ledger is cheap to read and changes whenever the agent computes
    // something, so it is re-read on every open regardless of the probe's
    // staleness window.
    readResults()
    if (probeOnOpen && stale()) refresh()
  }

  function readInventory() {
    if (runtimeDir === "" || inventoryProcess.running) return
    inventoryProcess.reset()
    inventoryProcess.command = ["/usr/bin/cat", runtimeDir + "/capability_inventory_v1.json"]
    inventoryProcess.running = true
  }

  // The ledger is written by another process between opens, so it is re-read
  // every time rather than kept. A missing file is an empty list, not an error:
  // "nothing computed yet" is a true and ordinary state.
  function readResults() {
    if (resultsProcess.running) {
      resultsReadQueued = true
      return
    }
    resultsReadQueued = false
    resultsProcess.reset()
    resultsProcess.command = ["/usr/bin/cat", "--", resultsPath]
    resultsProcess.running = true
  }

  function readNonClaim() {
    if (runtimeDir === "" || maturityProcess.running) return
    maturityProcess.reset()
    maturityProcess.command = [runtimeDir + "/jackal-native", "maturity"]
    maturityProcess.running = true
  }

  // Verify whatever the clipboard holds against the operator's standing
  // authorization. Refusal is a result, not an error: it is reported, never
  // retried on weaker terms.
  function verifyArtifact() {
    verifyPath("", "clipboard artifact")
  }

  // Re-verify a RETAINED receipt: the same front door, the same operator-owned
  // authorization, only a different transport for the artifact.
  //
  // This is what turns a LATEST RESULTS row from recall back into evidence. The
  // row itself proves nothing — it is a line this widget's wrapper wrote. The
  // retained receipt can be taken to `jackal_verify_receipt` and re-checked, and
  // if the operator's expectations do not authorize that exact request it
  // refuses. A refusal here is the correct answer, not a malfunction.
  function verifyReceiptDigest(digest) {
    // The path is DERIVED from the digest, never taken from the ledger. The
    // ledger is an ordinary file this widget's wrapper writes; treating a string
    // in it as a filesystem path to hand to a subprocess would let anything that
    // could edit that file choose what gets read. A 64-hex digest cannot name a
    // directory, a traversal, or a device.
    var d = String(digest || "")
    if (!/^[0-9a-f]{64}$/.test(d)) return
    verifyPath(receiptsDir + "/" + d + ".json", "retained receipt")
  }

  function verifyPath(artifactFile, description) {
    if (artifactProcess.running || runtimeDir === "") return
    artifactProcess.reset()
    var cmd = [
      "/usr/bin/python3", "-B", pluginDir + "/verify_artifact.py",
      "--runtime", runtimeDir,
      "--expectations", expectationsPath,
      "--now-unix", String(Math.floor(Date.now() / 1000))
    ]
    if (artifactFile !== "") cmd.push("--artifact-file", artifactFile)
    artifactProcess.command = cmd
    actionStatus = "Verifying " + description + "…"
    artifactProcess.running = true
  }

  function runVerify() {
    if (verifyProcess.running) return
    verifyProcess.reset()
    actionStatus = "Verifying runtime…"
    verifyProcess.running = true
  }

  // Everything the panel can put on the clipboard goes out through here, so
  // there is one place that decides what leaves the widget.
  function copyText(text, description) {
    var value = String(text || "")
    if (value === "") return
    copyProcess.running = false
    copyProcess.command = ["/usr/bin/wl-copy", "--", value]
    copyProcess.running = true
    actionStatus = "Copied " + description
    statusClear.restart()
  }

  function applyDoctor(raw, stderrText, exitCode) {
    var parsed = null
    if (String(raw).trim() !== "") {
      try {
        parsed = JSON.parse(raw)
      } catch (e) {
        parsed = null
      }
    }

    // A run that produced no parsable payload establishes nothing. Keeping the
    // previous report would let a dead CLI keep asserting a pass, so the
    // failure replaces it.
    if (!parsed) {
      lastError = stderrText !== "" ? stderrText
        : (exitCode === 127 ? "bundled omarchy-jackal could not execute"
                            : "doctor produced no parsable report")
      report = { error: lastError, receivedAtMs: Date.now() }
    } else {
      parsed.receivedAtMs = Date.now()
      lastError = ""
      report = parsed
    }

    receivedAtMs = report.receivedAtMs
    nowMs = receivedAtMs
    actionStatus = ""
  }

  Component.onCompleted: nowMs = Date.now()

  // Keep LATEST ANSWER live while the dropdown remains open. FileView is only
  // a change notification here; the normal process path still performs the
  // read and clears results on failure. The debounce also absorbs the atomic
  // replace sequence used by the ledger writer.
  FileView {
    id: resultsFileWatch
    path: root.resultsPath
    watchChanges: true
    onFileChanged: resultsRefresh.restart()
  }

  // Exit and stream-finished arrive in no guaranteed order, so both paths
  // report in and the last one to arrive does the work.
  Process {
    id: doctorProcess
    command: [root.pluginDir + "/bin/omarchy-jackal", "doctor", "--json"]

    property string outText: ""
    property string errText: ""
    property int exitCode: 0
    property bool exited: false
    property bool outDone: false
    property bool errDone: false

    function reset() {
      outText = ""; errText = ""; exitCode = 0
      exited = false; outDone = false; errDone = false
    }

    function settle() {
      if (!exited || !outDone || !errDone) return
      root.applyDoctor(outText, errText.trim(), exitCode)
    }

    stdout: StdioCollector {
      waitForEnd: true
      onStreamFinished: {
        doctorProcess.outText = String(text || "")
        doctorProcess.outDone = true
        doctorProcess.settle()
      }
    }
    stderr: StdioCollector {
      waitForEnd: true
      onStreamFinished: {
        doctorProcess.errText = String(text || "")
        doctorProcess.errDone = true
        doctorProcess.settle()
      }
    }
    onExited: function(code) {
      doctorProcess.exitCode = code
      doctorProcess.exited = true
      doctorProcess.settle()
    }
  }

  Process {
    id: verifyProcess
    command: [root.pluginDir + "/bin/omarchy-jackal", "verify"]

    property string outText: ""
    property bool exited: false
    property bool outDone: false

    function reset() { outText = ""; exited = false; outDone = false }

    function settle() {
      if (!exited || !outDone) return
      var parsed = null
      try {
        parsed = JSON.parse(outText)
      } catch (e) {
        parsed = null
      }
      root.verifyReport = parsed || { verify: "FAIL" }
      root.actionStatus = "Runtime verify: " + String(root.verifyReport.verify || "FAIL")
      statusClear.restart()
    }

    stdout: StdioCollector {
      waitForEnd: true
      onStreamFinished: {
        verifyProcess.outText = String(text || "")
        verifyProcess.outDone = true
        verifyProcess.settle()
      }
    }
    onExited: function(code) {
      verifyProcess.exited = true
      verifyProcess.settle()
    }
  }

  Process {
    id: inventoryProcess
    command: ["true"]

    property string outText: ""
    property bool exited: false
    property bool outDone: false
    property int exitCode: 0

    function reset() { outText = ""; exited = false; outDone = false; exitCode = 0 }

    function settle() {
      if (!exited || !outDone) return
      // An inventory we could not read, or one whose schema we do not know,
      // clears the register rather than leaving the previous runtime's
      // declarations on screen under a new epoch.
      root.inventory = exitCode === 0 ? Model.parseInventory(outText) : null
    }

    stdout: StdioCollector {
      waitForEnd: true
      onStreamFinished: {
        inventoryProcess.outText = String(text || "")
        inventoryProcess.outDone = true
        inventoryProcess.settle()
      }
    }
    onExited: function(code) {
      inventoryProcess.exitCode = code
      inventoryProcess.exited = true
      inventoryProcess.settle()
    }
  }

  // The results ledger. A missing or unreadable file yields an empty list —
  // "nothing computed yet" and "could not read" both establish nothing, and
  // neither may leave a previous session's answers on screen as if they were
  // current.
  Process {
    id: resultsProcess
    command: ["true"]

    property string outText: ""
    property bool exited: false
    property bool outDone: false
    property int exitCode: 0

    function reset() { outText = ""; exited = false; outDone = false; exitCode = 0 }

    function settle() {
      if (!exited || !outDone) return
      root.results = exitCode === 0 ? Model.parseResults(outText) : []
      if (root.resultsReadQueued) {
        root.resultsReadQueued = false
        resultsRefresh.restart()
      }
    }

    stdout: StdioCollector {
      waitForEnd: true
      onStreamFinished: {
        resultsProcess.outText = String(text || "")
        resultsProcess.outDone = true
        resultsProcess.settle()
      }
    }
    onExited: function(code) {
      resultsProcess.exitCode = code
      resultsProcess.exited = true
      resultsProcess.settle()
    }
  }

  Process {
    id: maturityProcess
    command: ["true"]

    property string outText: ""
    property bool exited: false
    property bool outDone: false
    property int exitCode: 0

    function reset() { outText = ""; exited = false; outDone = false; exitCode = 0 }

    function settle() {
      if (!exited || !outDone) return
      root.nonClaim = exitCode === 0 ? Model.parseNonClaim(outText) : ""
    }

    stdout: StdioCollector {
      waitForEnd: true
      onStreamFinished: {
        maturityProcess.outText = String(text || "")
        maturityProcess.outDone = true
        maturityProcess.settle()
      }
    }
    onExited: function(code) {
      maturityProcess.exitCode = code
      maturityProcess.exited = true
      maturityProcess.settle()
    }
  }

  Process {
    id: artifactProcess
    command: ["true"]

    property string outText: ""
    property string errText: ""
    property bool exited: false
    property bool outDone: false
    property bool errDone: false

    function reset() {
      outText = ""; errText = ""; exited = false; outDone = false; errDone = false
    }

    function settle() {
      if (!exited || !outDone || !errDone) return
      var parsed = null
      try {
        parsed = JSON.parse(outText)
      } catch (e) {
        parsed = null
      }
      // A router that produced no parsable verdict established nothing. Saying
      // so is the honest outcome; keeping the previous verdict on screen would
      // let a dead run keep asserting a pass.
      root.verifyResult = (parsed && parsed.schema === Model.VERIFY_SCHEMA)
        ? parsed
        : { schema: Model.VERIFY_SCHEMA, status: "indeterminate",
            reason: "widget-router-unparsable", raised_by: "widget",
            detail: errText.trim() || "verify_artifact.py produced no verdict" }
      root.actionStatus = "Clipboard artifact: " + String(root.verifyResult.status)
      statusClear.restart()
    }

    stdout: StdioCollector {
      waitForEnd: true
      onStreamFinished: {
        artifactProcess.outText = String(text || "")
        artifactProcess.outDone = true
        artifactProcess.settle()
      }
    }
    stderr: StdioCollector {
      waitForEnd: true
      onStreamFinished: {
        artifactProcess.errText = String(text || "")
        artifactProcess.errDone = true
        artifactProcess.settle()
      }
    }
    onExited: function(code) {
      artifactProcess.exited = true
      artifactProcess.settle()
    }
  }

  Process {
    id: copyProcess
    command: ["/usr/bin/wl-copy", "--", ""]
  }

  Timer {
    id: statusClear
    interval: 2600
    repeat: false
    onTriggered: root.actionStatus = ""
  }

  Timer {
    id: resultsRefresh
    interval: 160
    repeat: false
    onTriggered: root.readResults()
  }

  // The first probe is deferred so the shell's startup path is not paying for a
  // second of subprocess work before the bar has drawn.
  Timer {
    interval: 4000
    running: true
    repeat: false
    onTriggered: root.refresh()
  }

  Timer {
    interval: Math.max(60, root.refreshIntervalSec) * 1000
    running: true
    repeat: true
    onTriggered: root.refresh()
  }

  // Cheap clock so staleness and "probed 12m ago" stay truthful between probes.
  Timer {
    interval: 15000
    running: true
    repeat: true
    onTriggered: root.nowMs = Date.now()
  }
}
